import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050b14', // Richer deep dark blue/black
  },
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#050b14',
  },
  welcomeScroll: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  welcomeLogoText: {
    fontFamily: Platform.select({ ios: 'System', android: 'sans-serif-light', default: 'sans-serif' }),
    fontSize: 52,
    letterSpacing: -1.5,
    marginTop: 20,
    marginBottom: 20,
  },
  headerLogoImage: {
    width: 100,
    height: 35,
    resizeMode: 'contain', contentFit: 'contain',
  },
  headerLogoText: {
    fontFamily: Platform.select({ ios: 'System', android: 'sans-serif-light', default: 'sans-serif' }),
    fontSize: 24,
    letterSpacing: -0.8,
  },
  headerSpacer: {
    height: 30,
  },
  welcomeSubtitle: {
    fontSize: 15,
    color: '#9ca3af',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 30,
    maxWidth: 320,
  },
  loginCard: {
    width: '100%',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 24,
    padding: 20,
  },
  authTabs: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  authTabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  authTabBtnActive: {
    backgroundColor: '#0ea5e9',
  },
  authTabText: {
    color: '#9ca3af',
    fontWeight: '600',
    fontSize: 14,
  },
  authTabTextActive: {
    color: '#ffffff',
  },
  inputLabel: {
    fontSize: 13,
    color: '#9ca3af',
    fontWeight: '600',
    marginBottom: 6,
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 16,
    color: '#ffffff',
    fontSize: 16,
    marginBottom: 16,
  },
  loginBtn: {
    backgroundColor: '#0ea5e9',
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  loginBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  dividerText: {
    color: '#6b7280',
    marginHorizontal: 10,
    fontSize: 12,
    fontWeight: '600',
  },
  disclaimer: {
    color: '#6b7280',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 30,
  },

  // Feed Header
  appHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  appHeaderTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.5,
  },
  newInquiryBtnHeader: {
    backgroundColor: '#f97316',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  newInquiryBtnTextHeader: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  menuBtnHeader: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  menuBtnTextHeader: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },

  // Sidebar Styles
  sidebarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  sidebarDrawer: {
    width: '75%',
    height: '100%',
    backgroundColor: '#0f172a',
    borderLeftWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingTop: 50,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: -4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  sidebarProfileHeader: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 10,
  },
  sidebarAvatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(14, 165, 233, 0.1)',
    borderWidth: 1,
    borderColor: '#0ea5e9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  sidebarAvatarEmoji: {
    fontSize: 28,
  },
  sidebarAgencyName: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 4,
  },
  sidebarCity: {
    color: '#0ea5e9',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  sidebarPhone: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '600',
  },
  sidebarDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    marginVertical: 10,
  },
  sidebarMenuItems: {
    paddingVertical: 10,
    flexGrow: 1,
  },
  sidebarMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.03)',
    gap: 12,
  },
  sidebarMenuIcon: {
    fontSize: 18,
    width: 24,
    textAlign: 'center',
  },
  sidebarMenuText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  sidebarSpacing: {
    flex: 1,
    minHeight: 100,
  },
  sidebarLogoutItem: {
    borderBottomWidth: 0,
    marginTop: 'auto',
    paddingBottom: 30,
  },
  textRed: {
    color: '#ef4444',
  },

  // TabBar
  tabBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginTop: 10,
    gap: 8,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  activeTab: {
    backgroundColor: 'rgba(14, 165, 233, 0.15)',
    borderColor: '#0ea5e9',
  },
  tabText: {
    color: '#9ca3af',
    fontWeight: '600',
    fontSize: 12,
  },
  activeTabText: {
    color: '#0ea5e9',
  },
  refreshLoadingContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    marginBottom: 4,
    gap: 8,
  },
  refreshLoadingText: {
    color: '#0ea5e9',
    fontSize: 12,
    fontWeight: '700',
  },


  // Feed Container
  feedContent: {
    paddingHorizontal: 0,
    paddingTop: 15,
    paddingBottom: 120, // Clears floating nav bar (64px) + bottom inset + buffer
  },

  // Premium Instagram Card Layout
  igCard: {
    backgroundColor: '#0d1527',
    borderRadius: 0,
    marginBottom: 16,
    overflow: 'hidden',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    borderTopWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  igCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.03)',
  },
  deletePostBtn: {
    padding: 6,
    opacity: 0.6,
  },
  deletePostBtnText: {
    fontSize: 15,
  },
  headerB2B: {
    backgroundColor: 'rgba(245, 158, 11, 0.22)',
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(245, 158, 11, 0.45)',
  },
  headerHotel: {
    backgroundColor: 'rgba(168, 85, 247, 0.07)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(168, 85, 247, 0.15)',
  },
  actionMenuContent: {
    backgroundColor: '#0f172a',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    width: '90%',
    maxWidth: 320,
    overflow: 'hidden',
  },
  actionMenuBody: {
    paddingVertical: 12,
  },
  actionMenuTitle: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    marginBottom: 4,
    paddingHorizontal: 16,
  },
  actionMenuItem: {
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.03)',
  },
  actionMenuDeleteText: {
    color: '#ef4444',
    fontWeight: '700',
    fontSize: 14,
  },
  actionMenuReportText: {
    color: '#f97316',
    fontWeight: '600',
    fontSize: 14,
  },
  actionMenuText: {
    color: '#ffffff',
    fontSize: 14,
  },
  actionMenuCancel: {
    borderBottomWidth: 0,
    marginTop: 4,
  },
  actionMenuCancelText: {
    color: '#6b7280',
    fontSize: 14,
    fontWeight: '600',
  },
  igHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  avatarB2B: {
    borderColor: '#0ea5e9',
  },
  avatarB2C: {
    borderColor: '#f97316',
  },
  typeIndicatorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginLeft: 8,
    marginRight: 4,
  },
  bgB2B: {
    backgroundColor: '#0ea5e9',
  },
  bgB2C: {
    backgroundColor: '#f97316',
  },
  bgGuidance: {
    backgroundColor: '#a855f7',
  },
  bgShowcase: {
    backgroundColor: '#10b981',
  },
  typeIndicatorText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  textB2B: {
    color: '#0ea5e9',
  },
  textB2C: {
    color: '#f97316',
  },
  textGuidance: {
    color: '#a855f7',
  },
  textShowcase: {
    color: '#10b981',
  },
  avatarEmoji: {
    fontSize: 18,
  },
  avatarVerifiedBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#0ea5e9',
    borderRadius: 8,
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#0d1527',
  },
  avatarVerifiedText: {
    color: '#ffffff',
    fontSize: 9,
    fontWeight: '900',
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  igAuthorName: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  verifiedBadge: {
    color: '#0ea5e9',
    fontSize: 12,
    fontWeight: '900',
  },
  igTime: {
    color: '#6b7280',
    fontSize: 11,
  },
  typeBadge: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  b2bBadge: {
    backgroundColor: 'rgba(14, 165, 233, 0.15)',
  },
  b2cBadge: {
    backgroundColor: 'rgba(249, 115, 22, 0.15)',
  },
  typeBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#ffffff',
  },
  igCardContent: {
    padding: 14,
  },
  igCardTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 6,
  },
  igCardDescription: {
    color: '#d1d5db',
    fontSize: 13.5,
    lineHeight: 18.5,
  },
  igMediaImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover', contentFit: 'cover',
  },
  igLightCard: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  igLightCardAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
  },
  igLightCardBody: {
    padding: 16,
    paddingLeft: 20,
  },
  igLightCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  igLightCardLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#64748b',
    letterSpacing: 0.5,
  },
  igLightCardTag: {
    fontSize: 10,
    fontWeight: '700',
    color: '#3b82f6',
  },
  igLightCardDest: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  igLightCardPrice: {
    fontSize: 13,
    fontWeight: '800',
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: 'rgba(0,0,0,0.03)',
  },
  igStatPanel: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.03)',
  },
  igPriceText: {
    fontSize: 14,
    fontWeight: '800',
  },
  priceTeal: {
    color: '#0ea5e9',
  },
  priceOrange: {
    color: '#f97316',
  },
  tagRow: {
    flexDirection: 'row',
    gap: 6,
  },
  igTag: {
    color: '#0ea5e9',
    fontSize: 11.5,
    fontWeight: '600',
  },
  igActionBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.03)',
    paddingVertical: 10,
    paddingHorizontal: 12,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  actionButtonText: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  whatsappButton: {
    backgroundColor: '#25d366',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  whatsappButtonText: {
    color: '#ffffff',
    fontSize: 11.5,
    fontWeight: '700',
  },
  emptyText: {
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 40,
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#0d1527',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 24,
    padding: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 16,
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9ca3af',
    marginBottom: 6,
  },
  categoryTabsContainer: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
  },
  categoryTab: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTabActive: {
    backgroundColor: '#0284c7',
    borderColor: '#38bdf8',
  },
  categoryTabText: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  categoryTabTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  modalInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 16,
    color: '#ffffff',
    fontSize: 16,
    marginBottom: 16,
  },
  modalInputTextarea: {
    height: 80,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
  modalActionGroup: {
    flexDirection: 'row',
    gap: 12,
  },
  modalBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnCancel: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  modalBtnCancelText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  modalBtnSubmit: {
    backgroundColor: '#f97316',
  },
  modalBtnSubmitText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  modalScrollContent: {
    paddingVertical: 40,
    justifyContent: 'center',
  },
  sidebarAvatarImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    resizeMode: 'cover', contentFit: 'cover',
  },
  avatarImage: {
    width: 34,
    height: 34,
    borderRadius: 17,
    resizeMode: 'cover', contentFit: 'cover',
  },
  logoTabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 3,
    marginBottom: 16,
  },
  logoTabBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 7,
  },
  logoTabBtnActive: {
    backgroundColor: '#0ea5e9',
  },
  logoTabBtnText: {
    color: '#9ca3af',
    fontWeight: '600',
    fontSize: 12,
  },
  logoTabBtnTextActive: {
    color: '#ffffff',
  },
  presetsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
    justifyContent: 'center',
  },
  presetItem: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetItemActive: {
    backgroundColor: 'rgba(14, 165, 233, 0.15)',
    borderColor: '#0ea5e9',
    borderWidth: 2,
  },
  presetText: {
    fontSize: 20,
  },
  customCropContainer: {
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
  },
  uploadBtn: {
    backgroundColor: 'rgba(14, 165, 233, 0.1)',
    borderWidth: 1,
    borderColor: '#0ea5e9',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 20,
    width: '100%',
    alignItems: 'center',
    marginBottom: 12,
  },
  uploadBtnText: {
    color: '#0ea5e9',
    fontWeight: '700',
    fontSize: 13,
  },
  noImageText: {
    color: '#6b7280',
    fontSize: 12,
    fontStyle: 'italic',
    textAlign: 'center',
    marginVertical: 10,
  },
  cropperWrapper: {
    alignItems: 'center',
    width: '100%',
  },
  cropInstruction: {
    color: '#9ca3af',
    fontSize: 11,
    marginBottom: 8,
  },
  cropViewport: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    marginBottom: 12,
  },
  circleOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 90,
    borderWidth: 2,
    borderColor: '#0ea5e9',
    backgroundColor: 'transparent',
  },
  controlRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    paddingHorizontal: 10,
  },
  controlLabel: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: 8,
  },
  controlBtn: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlBtnText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  dpadContainer: {
    width: '100%',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  dpadGrid: {
    alignItems: 'center',
    marginTop: 8,
  },
  dpadBtn: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    width: 42,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dpadBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  // Centered Header Styles
  headerIconLeft: {
    padding: 8,
  },
  headerIconText: {
    fontSize: 20,
    color: '#0ea5e9',
  },
  appHeaderTitleCent: {
    fontSize: 22,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  headerRightSpacer: {
    width: 36, // Match the left icon button width for perfect centering
  },
  // Floating Bottom Console Styles
  // Note: `bottom` is applied dynamically in FloatingConsole via useSafeAreaInsets
  floatingBottomConsole: {
    position: 'absolute',
    left: 16,
    right: 16,
    height: 68,
    borderRadius: 34,
    backgroundColor: 'rgba(10, 18, 35, 0.97)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 12,
    backdropFilter: 'blur(20px)',
  },
  consoleTab: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 24,
  },
  consoleTabActive: {
    // No background — active state is icon/text color only
  },
  consoleIcon: {
    fontSize: 26,
    color: '#4b5563',
    lineHeight: 30,
  },
  consoleIconActive: {
    color: '#0ea5e9',
  },
  consoleText: {
    fontSize: 10,
    color: '#4b5563',
    fontWeight: '600',
    marginTop: 3,
    letterSpacing: 0.2,
  },
  consoleTextActive: {
    color: '#0ea5e9',
    fontWeight: '700',
  },
  // Inline Profile View Styles
  inlineProfileScroll: {
    paddingTop: 10,
    paddingBottom: 120,
  },
  inlineProfileContent: {
    backgroundColor: '#0d1527',
    marginHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  inlineProfileTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 20,
    textAlign: 'center',
  },
  profileLogoutBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
    borderRadius: 12,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    width: '100%',
  },
  profileLogoutBtnText: {
    color: '#ef4444',
    fontWeight: '700',
    fontSize: 13,
  },
  segmentedContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  segmentBtnActive: {
    backgroundColor: '#0ea5e9',
  },
  segmentBtnActiveB2C: {
    backgroundColor: '#f97316',
  },
  segmentBtnActiveB2B: {
    backgroundColor: '#10b981',
  },
  segmentBtnActiveBoth: {
    backgroundColor: '#6366f1',
  },
  segmentBtnText: {
    color: '#9ca3af',
    fontWeight: '600',
    fontSize: 13,
  },
  segmentBtnTextActive: {
    color: '#ffffff',
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  chip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  chipActive: {
    backgroundColor: 'rgba(14, 165, 233, 0.15)',
    borderColor: '#0ea5e9',
  },
  chipText: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#0ea5e9',
  },
  // Instagram Profile View Styles
  profileHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    backgroundColor: '#050b14',
  },
  profileBackBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  profileBackText: {
    color: '#0ea5e9',
    fontSize: 14,
    fontWeight: '700',
  },
  profileHeaderTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
    flex: 1,
  },
  profileHeaderVerifyBadge: {
    color: '#0ea5e9',
    fontSize: 16,
    fontWeight: '900',
    marginLeft: 4,
  },
  igProfileScroll: {
    paddingBottom: 130, // Clears floating nav bar + bottom inset
  },
  igProfileInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    gap: 20,
  },
  igProfileAvatarContainer: {
    alignItems: 'center',
  },
  igLargeAvatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: '#0ea5e9',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  igLargeAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 36,
    resizeMode: 'cover', contentFit: 'cover',
  },
  igLargeAvatarEmoji: {
    fontSize: 36,
  },
  igLargeAvatarVerifiedBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#0ea5e9',
    borderRadius: 14,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#0d1527',
  },
  igLargeAvatarVerifiedText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  igStatsRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  igStatCol: {
    alignItems: 'center',
  },
  igStatNum: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  igStatLabel: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
  },
  igBioContainer: {
    paddingHorizontal: 20,
    marginTop: 14,
  },
  igBioName: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  igBioCity: {
    color: '#9ca3af',
    fontSize: 12,
    marginTop: 2,
    fontWeight: '600',
  },
  igBioTypeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(14, 165, 233, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(14, 165, 233, 0.25)',
    borderRadius: 6,
    paddingVertical: 3,
    paddingHorizontal: 8,
    color: '#0ea5e9',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 6,
  },
  bioTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  bioTag: {
    color: '#0ea5e9',
    fontSize: 12,
    fontWeight: '600',
  },
  gstinBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignSelf: 'flex-start',
  },
  gstinBadgeText: {
    color: '#10b981',
    fontSize: 11.5,
    fontWeight: '700',
  },
  igProfileActionsRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 16,
    gap: 10,
  },
  igProfileBtn: {
    flex: 1,
    height: 38,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  igProfileBtnPrimary: {
    backgroundColor: '#0ea5e9',
    borderColor: '#0ea5e9',
  },
  igProfileBtnSecondary: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  igProfileBtnDanger: {
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  igProfileBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  igGridTabsBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    marginTop: 20,
    height: 44,
  },
  igGridTabBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  igGridTabBtnActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#ffffff',
  },
  igGridTabIcon: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '600',
  },
  igGridTabIconActive: {
    color: '#ffffff',
  },
  igEmptyGridContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 30,
  },
  igEmptyGridText: {
    color: '#6b7280',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: 20,
  },
  igGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 1,
    paddingTop: 1,
  },
  igGridCell: {
    width: '33.33%',
    aspectRatio: 1,
    padding: 2,
  },
  igGridCellImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
    resizeMode: 'cover', contentFit: 'cover',
  },
  igGridCellTextCard: {
    width: '100%',
    height: '100%',
    borderRadius: 4,
    padding: 8,
    justifyContent: 'space-between',
  },
  gridBgB2B: {
    backgroundColor: 'rgba(14, 165, 233, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(14, 165, 233, 0.2)',
  },
  gridBgB2C: {
    backgroundColor: 'rgba(249, 115, 22, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(249, 115, 22, 0.2)',
  },
  igGridCellEmoji: {
    fontSize: 16,
  },
  igGridCellTitle: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
  },
  // Instagram Edit Profile Styles
  editProfileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#0d1527',
  },
  editHeaderBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  editHeaderBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
  },
  editHeaderTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  editProfileScroll: {
    paddingBottom: 60,
  },
  editAvatarSection: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  changePhotoText: {
    color: '#0ea5e9',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 10,
  },
  editPhotoAccordion: {
    backgroundColor: '#0d1527',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  editFormSection: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    backgroundColor: '#0d1527',
    marginTop: 10,
  },
  editFormRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.04)',
  },
  editFormLabel: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '600',
    width: 90,
  },
  editFormValueContainer: {
    flex: 1,
  },
  editRowInput: {
    color: '#ffffff',
    fontSize: 16,
    paddingVertical: 4,
  },
  editSpecSection: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  editSectionTitle: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '600',
  },
  profileDetailsCard: {
    backgroundColor: '#0d1527',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  profileDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.03)',
  },
  profileDetailLabel: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
    width: 110,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  profileDetailValue: {
    color: '#ffffff',
    fontSize: 13.5,
    fontWeight: '500',
    flex: 1,
  },
  editFormCard: {
    backgroundColor: '#0d1527',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  editFormInputGroup: {
    marginBottom: 16,
  },
  editFormInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 8,
    color: '#ffffff',
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  editFormLockedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  requestChangeBtn: {
    backgroundColor: 'rgba(14, 165, 233, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(14, 165, 233, 0.3)',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  requestChangeBtnText: {
    color: '#0ea5e9',
    fontSize: 11.5,
    fontWeight: '700',
  },
  pinInputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
    gap: 8,
    marginBottom: 20,
  },
  pinInputBox: {
    flex: 1,
    height: 48,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    maxWidth: 45,
    textAlign: 'center',
  },

  // ============================================================
  // Profile Redesign: Stats, Follow, Uniform Cards
  // ============================================================

  // --- Profile Stats Row (Posts / Followers / Following) ---
  profileStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 4,
  },
  profileStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  profileStatCount: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  profileStatLabel: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
    letterSpacing: 0.2,
  },
  profileStatDivider: {
    width: 1,
    height: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },

  // --- Follow / Following Button ---
  followBtn: {
    flex: 1,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0ea5e9',
  },
  followBtnActive: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  followBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  followBtnTextActive: {
    color: '#9ca3af',
  },
  messageBtn: {
    flex: 1,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  messageBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },

  // --- Uniform Profile Grid Cards ---
  profileGridCard: {
    width: '100%',
    height: '100%',
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#1a1f2e',
  },
  profileGridCardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover', contentFit: 'cover',
  },
  profileGridCardOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.50)',
  },
  profileGridCardLabel: {
    color: '#d1d5db',
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  // Text-only grid card (no image)
  profileGridCardText: {
    width: '100%',
    height: '100%',
    borderRadius: 4,
    backgroundColor: '#1a1f2e',
    padding: 10,
    justifyContent: 'space-between',
  },
  profileGridCardTitle: {
    color: '#e2e8f0',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  profileGridCardDesc: {
    color: '#6b7280',
    fontSize: 9,
    fontWeight: '400',
    marginTop: 3,
    lineHeight: 12,
  },
  profileGridCardFooter: {
    marginTop: 'auto',
  },
  profileGridCardFooterText: {
    color: '#6b7280',
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },

  // Profile Tabs Styles
  profileTabsContainer: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    marginBottom: 8,
  },
  profileTabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  profileTabButtonActive: {
    borderBottomColor: '#0ea5e9',
  },
  profileTabText: {
    color: '#6b7280',
    fontSize: 13,
    fontWeight: '700',
  },
  profileTabTextActive: {
    color: '#0ea5e9',
  },

  // Comments Modal Styles
  commentsOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
  },
  commentsContainer: {
    backgroundColor: '#0d1527',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: '75%',
    width: '100%',
    paddingBottom: Platform.OS === 'ios' ? 24 : 10,
    borderTopWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  commentsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  commentsTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  commentsCloseBtn: {
    padding: 4,
  },
  commentsListContent: {
    padding: 16,
  },
  commentItem: {
    flexDirection: 'row',
    marginBottom: 16,
    alignItems: 'flex-start',
  },
  commentAuthorName: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  commentText: {
    color: '#d1d5db',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  commentsEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  commentsEmptyText: {
    color: '#6b7280',
    fontSize: 12,
    textAlign: 'center',
  },
  commentInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    backgroundColor: '#0d1527',
  },
  commentInput: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    maxHeight: 80,
    color: '#ffffff',
    fontSize: 16,
  },
  commentSendBtn: {
    marginLeft: 12,
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Post Action Icon bar
  actionIconsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  actionIconButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
  },
  actionIconLabel: {
    color: '#9ca3af',
    fontSize: 11.5,
    fontWeight: '600',
  },
  cleanWhatsappBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  cleanWhatsappBtnText: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '600',
  },
});
